# Generated by Django 4.2.29 on 2026-03-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
