# Generated by Django 4.2.29 on 2026-03-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0002_users_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviegenres',
            unique_together={('movie', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendations',
            unique_together={('user', 'movie')},
        ),
    ]
