# Generated by Django 4.2.29 on 2026-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_app', '0003_alter_moviegenres_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default=1, upload_to='posters/'),
            preserve_default=False,
        ),
    ]
